name: Domain Request
description: Use this form to create a domain request
title: "[Request]: "
labels:
  - "request: domain"
assignees:
  - hkamran80
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting a domain!
  - type: input
    id: domain
    attributes:
      label: Domain
      description: The URL, excluding the protocol (`http`, `https`)
      placeholder: example.com
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Why should this domain be added?
    validations:
      required: false
  - type: dropdown
    id: list
    attributes:
      label: List
      description: Which blocklist would you like to add this domain to?
      multiple: true
      options:
        - Smart TV
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
    validations:
      required: false
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/hkamran80/blocklists/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
